In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
data1 = pd.read_csv(r'train_jqd04QH.csv')
data1.head()


enrollee_id      city  city_development_index gender  \
0        23798  city_149                   0.689   Male   
1        29166   city_83                   0.923   Male   
2           46   city_16                   0.910    NaN   
3        18527   city_64                   0.666   Male   
4        21751  city_100                   0.887    NaN   

       relevent_experience enrolled_university education_level  \
0  Has relevent experience       no_enrollment        Graduate   
1  Has relevent experience       no_enrollment        Graduate   
2  Has relevent experience       no_enrollment        Graduate   
3  Has relevent experience       no_enrollment        Graduate   
4   No relevent experience       no_enrollment         Masters   

  major_discipline experience company_size    company_type last_new_job  \
0             STEM          3      100-500         Pvt Ltd            1   
1             STEM         14          <10  Funded Startup            1   
2             STEM          6        50-99   Public Sector            2   
3             STEM         14        50-99         Pvt Ltd            1   
4             STEM          8          NaN             NaN            2   

   training_hours  target  
0             106       0  
1              69       0  
2               4       0  
3              26       0  
4              88       1

In [3]:
data1.info()
data1.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18359 entries, 0 to 18358
Data columns (total 14 columns):
enrollee_id               18359 non-null int64
city                      18359 non-null object
city_development_index    18359 non-null float64
gender                    14261 non-null object
relevent_experience       18359 non-null object
enrolled_university       18017 non-null object
education_level           17902 non-null object
major_discipline          15521 non-null object
experience                18300 non-null object
company_size              13580 non-null object
company_type              13320 non-null object
last_new_job              17992 non-null object
training_hours            18359 non-null int64
target                    18359 non-null int64
dtypes: float64(1), int64(3), object(10)
memory usage: 2.0+ MB


Index(['enrollee_id', 'city', 'city_development_index', 'gender',
       'relevent_experience', 'enrolled_university', 'education_level',
       'major_discipline', 'experience', 'company_size', 'company_type',
       'last_new_job', 'training_hours', 'target'],
      dtype='object')

In [4]:
data1.shape

(18359, 14)

In [5]:
data1.isnull().sum()

enrollee_id                  0
city                         0
city_development_index       0
gender                    4098
relevent_experience          0
enrolled_university        342
education_level            457
major_discipline          2838
experience                  59
company_size              4779
company_type              5039
last_new_job               367
training_hours               0
target                       0
dtype: int64

In [6]:
data1.drop(["enrollee_id"], axis=1, inplace = True)

In [7]:
### replace all missing genders with females
data1["gender"].fillna("Female", inplace = True) 

In [8]:
data1.dropna(subset=['enrolled_university', 'education_level','experience','last_new_job'], inplace=True)

In [9]:
data1.isnull().sum()

city                         0
city_development_index       0
gender                       0
relevent_experience          0
enrolled_university          0
education_level              0
major_discipline          2253
experience                   0
company_size              4228
company_type              4448
last_new_job                 0
training_hours               0
target                       0
dtype: int64

In [10]:
data1["major_discipline"].fillna("STEM", inplace = True) 

In [11]:
data1['company_type'].fillna("Pvt Ltd", inplace = True)

In [12]:
data1.isnull().sum()

city                         0
city_development_index       0
gender                       0
relevent_experience          0
enrolled_university          0
education_level              0
major_discipline             0
experience                   0
company_size              4228
company_type                 0
last_new_job                 0
training_hours               0
target                       0
dtype: int64

In [13]:
# Import label encoder 
from sklearn import preprocessing 
  
# label_encoder object knows how to understand word labels. 
label_encoder = preprocessing.LabelEncoder() 
  
# Encode labels in column 'species'. 
data1['city']= label_encoder.fit_transform(data1['city']) 
  
data1['city'].unique() 

array([ 41, 112,  48,  93,   2,  64,  13,   5, 120,  49,  94, 116, 103,
        30,  47,  95,   1, 101, 104,  70,   6,  69,  71,  91, 122,  36,
        15,  24, 102,  96,   0,  78,  21,  43,  51, 114,  74,  81,  83,
        82, 118,  60,  50, 113,  31,  55,  61,  77,  99,  46,  65,   4,
         7, 117,  11,  26,  89,  63,  33,  14,  85,  53,  18,  37,  22,
       105,   3,  42,  58,   9,  56,  57,  40, 121,  52,  17,  25,  66,
       110,  68, 119,  98,  39,  45,  29,  12,  75, 106, 109,  73,  97,
       100, 115,  80,  38,  76,  90,  84,  27,  20,  35,  79,  16,  88,
        87,  32,  92,  86,   8,  44,  28,  54,  62,  23,  19,  59,  72,
        10,  67, 108, 111,  34, 107], dtype=int64)

In [14]:
data1['gender']= label_encoder.fit_transform(data1['gender']) 
data1['gender'].unique() 

array([1, 0, 2], dtype=int64)

In [15]:
data1['relevent_experience']= label_encoder.fit_transform(data1['relevent_experience']) 
data1['relevent_experience'].unique()

array([0, 1], dtype=int64)

In [16]:
data1['enrolled_university']= label_encoder.fit_transform(data1['enrolled_university']) 
data1['enrolled_university'].unique()

array([2, 0, 1], dtype=int64)

In [17]:
data1['education_level']= label_encoder.fit_transform(data1['education_level']) 
data1['education_level'].unique()

array([0, 2, 1, 3, 4], dtype=int64)

In [18]:
data1['major_discipline']= label_encoder.fit_transform(data1['major_discipline']) 
data1['major_discipline'].unique()

array([5, 4, 3, 1, 0, 2], dtype=int64)

In [19]:
data1['experience']= label_encoder.fit_transform(data1['experience']) 
data1['experience'].unique()

array([13,  5, 16, 18, 21, 14, 19,  6,  1, 15,  7,  2,  3, 17, 11,  4, 20,
       10,  9,  0,  8, 12], dtype=int64)

In [20]:
data1= data1.astype({"company_size":'object'}) 
data1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 17315 entries, 0 to 18358
Data columns (total 13 columns):
city                      17315 non-null int32
city_development_index    17315 non-null float64
gender                    17315 non-null int32
relevent_experience       17315 non-null int32
enrolled_university       17315 non-null int32
education_level           17315 non-null int32
major_discipline          17315 non-null int32
experience                17315 non-null int32
company_size              13087 non-null object
company_type              17315 non-null object
last_new_job              17315 non-null object
training_hours            17315 non-null int64
target                    17315 non-null int64
dtypes: float64(1), int32(7), int64(2), object(3)
memory usage: 1.4+ MB


In [21]:
data1.replace(to_replace ="10/49", value ="1", inplace=True) 
data1.replace(to_replace ="100-500", value ="2", inplace=True) 
data1.replace(to_replace ="1000-4999", value ="3", inplace=True) 
data1.replace(to_replace ="10000+", value ="4", inplace=True) 
data1.replace(to_replace ="50-99", value ="5", inplace=True)
data1.replace(to_replace ="500-999", value ="6", inplace=True)
data1.replace(to_replace ="5000-9999", value ="7", inplace=True)
data1.replace(to_replace ="<10", value ="8", inplace=True)
data1.groupby('company_size').count()

city  city_development_index  gender  relevent_experience  \
company_size                                                              
1             1395                    1395    1395                 1395   
2             2613                    2613    2613                 2613   
3             1353                    1353    1353                 1353   
4             1998                    1998    1998                 1998   
5             2998                    2998    2998                 2998   
6              869                     869     869                  869   
7              571                     571     571                  571   
8             1290                    1290    1290                 1290   

              enrolled_university  education_level  major_discipline  \
company_size                                                           
1                            1395             1395              1395   
2                            2613             2613              2613   
3                            1353             1353              1353   
4                            1998             1998              1998   
5                            2998             2998              2998   
6                             869              869               869   
7                             571              571               571   
8                            1290             1290              1290   

              experience  company_type  last_new_job  training_hours  target  
company_size                                                                  
1                   1395          1395          1395            1395    1395  
2                   2613          2613          2613            2613    2613  
3                   1353          1353          1353            1353    1353  
4                   1998          1998          1998            1998    1998  
5                   2998          2998          2998            2998    2998  
6                    869           869           869             869     869  
7                    571           571           571             571     571  
8                   1290          1290          1290            1290    1290

In [22]:
data1['company_size'].value_counts()

5    2998
2    2613
4    1998
1    1395
3    1353
8    1290
6     869
7     571
Name: company_size, dtype: int64

In [23]:
data1.drop(['company_size'], axis=1,inplace=True)

In [24]:
data1['last_new_job']= label_encoder.fit_transform(data1['last_new_job']) 
data1['last_new_job'].unique()

array([0, 1, 2, 4, 5, 3], dtype=int64)

In [25]:
data1['company_type']= label_encoder.fit_transform(data1['company_type']) 
data1['company_type'].unique()

array([5, 1, 4, 0, 2, 3], dtype=int64)

In [26]:
data1= data1.astype({"city_development_index":'int64'}) 

In [27]:
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
std_data = pd.DataFrame(StandardScaler().fit_transform(data1))
std_data.columns = data1.columns

In [28]:
data1['target'].value_counts()

0    15064
1     2251
Name: target, dtype: int64

In [29]:
from sklearn.utils import resample

In [30]:
#Upsample minority classPython

# Separate majority and minority classes
df_majority = data1[data1.target==0]
df_minority = data1[data1.target==1]
 
# Upsample minority class
df_minority_upsampled = resample(df_minority, 
                                 replace=True,     # sample with replacement
                                 n_samples=15064,    # to match majority class
                                 random_state=150) # reproducible results
 
# Combine majority class with upsampled minority class
df_upsampled = pd.concat([df_majority, df_minority_upsampled])
 
# Display new class counts
df_upsampled.target.value_counts()


1    15064
0    15064
Name: target, dtype: int64

In [31]:
df_upsampled.shape

(30128, 12)

In [32]:
df_upsampled.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30128 entries, 0 to 8284
Data columns (total 12 columns):
city                      30128 non-null int64
city_development_index    30128 non-null int64
gender                    30128 non-null int64
relevent_experience       30128 non-null int64
enrolled_university       30128 non-null int64
education_level           30128 non-null int64
major_discipline          30128 non-null int64
experience                30128 non-null int64
company_type              30128 non-null int32
last_new_job              30128 non-null int32
training_hours            30128 non-null int64
target                    30128 non-null int64
dtypes: int32(2), int64(10)
memory usage: 2.8 MB


In [33]:
from sklearn.model_selection import train_test_split

X = df_upsampled.drop(["target"], axis=1) 
y = df_upsampled.target   
test_size = 0.20 
seed = 100
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=seed) 
type(X_train)

pandas.core.frame.DataFrame

In [34]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)


(24102, 11)
(24102,)
(6026, 11)
(6026,)


In [35]:
df_upsampled.isnull().sum()

city                      0
city_development_index    0
gender                    0
relevent_experience       0
enrolled_university       0
education_level           0
major_discipline          0
experience                0
company_type              0
last_new_job              0
training_hours            0
target                    0
dtype: int64

In [36]:
from sklearn.linear_model import LogisticRegression
from sklearn import model_selection
from sklearn import metrics
from sklearn.metrics import plot_confusion_matrix

model = LogisticRegression()
model.fit(X_train, y_train)
model_score = model.score(X_test, y_test)
y_predict = model.predict(X_test)

# check the accuracy on the training set
print("Training accuracy:" ,model.score(X_train, y_train))
print("Testing accuracy:", model.score(X_test, y_test))

print(metrics.confusion_matrix(y_test, y_predict))

Training accuracy: 0.5720272176582856
Testing accuracy: 0.5701958181214736
[[1919 1081]
 [1509 1517]]


C:\Users\Aakas\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [37]:
data2 = pd.read_csv(r'test_KaymcHn.csv')
data2.head()


enrollee_id      city  city_development_index gender  \
0        16548   city_33                   0.448    NaN   
1        12036   city_28                   0.939   Male   
2        11061  city_103                   0.920   Male   
3         5032  city_104                   0.924   Male   
4        17599   city_77                   0.830   Male   

       relevent_experience enrolled_university education_level  \
0   No relevent experience    Full time course        Graduate   
1   No relevent experience       no_enrollment        Graduate   
2   No relevent experience    Full time course        Graduate   
3   No relevent experience       no_enrollment             Phd   
4  Has relevent experience       no_enrollment        Graduate   

  major_discipline experience company_size   company_type last_new_job  \
0             STEM         <1    1000-4999  Public Sector          NaN   
1             STEM        >20        50-99        Pvt Ltd            1   
2             STEM          3          NaN            NaN            1   
3             STEM        >20        50-99        Pvt Ltd            2   
4             STEM          6          <10        Pvt Ltd            2   

   training_hours  
0              15  
1              94  
2              17  
3              76  
4              65

In [38]:
data2.shape

(15021, 13)

In [39]:
data2.isnull().sum()

enrollee_id                  0
city                         0
city_development_index       0
gender                    3388
relevent_experience          0
enrolled_university        279
education_level            395
major_discipline          2393
experience                  44
company_size              4051
company_type              4330
last_new_job               304
training_hours               0
dtype: int64

In [40]:
data2.shape


(15021, 13)

In [41]:
### replace all missing genders with females
data2["gender"].fillna("Female", inplace = True) 

In [42]:
data2.shape

(15021, 13)

In [43]:
##data2.dropna(subset=['enrolled_university', 'education_level','experience','last_new_job'], inplace=True)
data2["enrolled_university"].fillna( method ='ffill', inplace = True)
#data2= data2.astype({"enrolled_university":'int64'}) 

data2["education_level"].fillna( method ='ffill', inplace = True)
#data2= data2.astype({"education_level":'int64'})

data2["experience"].fillna( method ='ffill', inplace = True)
#data2= data2.astype({"experience":'int64'})

data2["last_new_job"].fillna( method ='ffill', inplace = True)
#data2= data2.astype({"last_new_job":'int64'})


In [44]:
data2.shape

(15021, 13)

In [45]:
data2.isnull().sum()

enrollee_id                  0
city                         0
city_development_index       0
gender                       0
relevent_experience          0
enrolled_university          0
education_level              0
major_discipline          2393
experience                   0
company_size              4051
company_type              4330
last_new_job                 1
training_hours               0
dtype: int64

In [46]:
data2['last_new_job'].fillna(data2['last_new_job'].mode()[0], inplace=True)

In [47]:
data2["major_discipline"].fillna("STEM", inplace = True) 

In [48]:
data2['company_type'].fillna("Pvt Ltd", inplace = True)

In [49]:
data2.shape

(15021, 13)

In [50]:
# Import label encoder 
from sklearn import preprocessing 
  
# label_encoder object knows how to understand word labels. 
label_encoder = preprocessing.LabelEncoder() 
  
# Encode labels in column 'species'. 
data2['city']= label_encoder.fit_transform(data2['city']) 
  
data2['city'].unique() 

array([ 73,  70,   5,   6, 105,  49,  64,  13,  48,  95,  85,  99,  30,
        90,   4,  89,   2,  55,  94,  74, 120,   0,  66,  91,  16,   3,
        26,   1, 103,  60,  34,  27,  31,  82, 102,  36,  83, 101,  35,
        45,  11,  15,  10, 114, 109,  76, 121,  78,  43, 122,  79,  37,
         7, 112, 117,  41,  29, 118,  63,  51,  65,  40,  24,  61, 113,
       104, 119,  23,  50, 116,  71,  86,  77,  19,  92,  21, 111,  46,
        53,  87,  17,  93,  20,  57,  98,  42,  47,  69,  28,  14,  59,
        54,  39,  81, 106,  38,  88, 115,  68,  22, 108,  58,  56,  44,
        80,  25,  18, 100,  75,  33, 107,  62,   8,  72, 110,  67,  96,
        97,   9,  84,  12,  52,  32], dtype=int64)

In [51]:
data2['gender']= label_encoder.fit_transform(data2['gender']) 
data2['gender'].unique() 

array([0, 1, 2], dtype=int64)

In [52]:
data2['relevent_experience']= label_encoder.fit_transform(data2['relevent_experience']) 
data2['relevent_experience'].unique()

array([1, 0], dtype=int64)

In [53]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15021 entries, 0 to 15020
Data columns (total 13 columns):
enrollee_id               15021 non-null int64
city                      15021 non-null int32
city_development_index    15021 non-null float64
gender                    15021 non-null int32
relevent_experience       15021 non-null int32
enrolled_university       15021 non-null object
education_level           15021 non-null object
major_discipline          15021 non-null object
experience                15021 non-null object
company_size              10970 non-null object
company_type              15021 non-null object
last_new_job              15021 non-null object
training_hours            15021 non-null int64
dtypes: float64(1), int32(3), int64(2), object(7)
memory usage: 1.3+ MB


In [54]:
data2['enrolled_university']= label_encoder.fit_transform(data2['enrolled_university']) 
data2['enrolled_university'].unique()

array([0, 2, 1], dtype=int64)

In [55]:
data2['education_level']= label_encoder.fit_transform(data2['education_level']) 
data2['education_level'].unique()

array([0, 3, 1, 2, 4], dtype=int64)

In [56]:
data2['major_discipline']= label_encoder.fit_transform(data2['major_discipline']) 
data2['major_discipline'].unique()

array([5, 0, 2, 4, 3, 1], dtype=int64)

In [57]:
data2['experience']= label_encoder.fit_transform(data2['experience']) 
data2['experience'].unique()

array([20, 21, 13, 16, 17, 19,  9, 11,  1,  5,  7, 15, 10,  8, 14, 18,  3,
        4, 12,  6,  0,  2], dtype=int64)

In [58]:
data2= data2.astype({"company_size":'object'}) 

In [59]:
data2.replace(to_replace ="10/49", value ="1", inplace=True) 
data2.replace(to_replace ="100-500", value ="2", inplace=True) 
data2.replace(to_replace ="1000-4999", value ="3", inplace=True) 
data2.replace(to_replace ="10000+", value ="4", inplace=True) 
data2.replace(to_replace ="50-99", value ="5", inplace=True)
data2.replace(to_replace ="500-999", value ="6", inplace=True)
data2.replace(to_replace ="5000-9999", value ="7", inplace=True)
data2.replace(to_replace ="<10", value ="8", inplace=True)
data2.groupby('company_size').count()

enrollee_id  city  city_development_index  gender  \
company_size                                                      
1                    1198  1198                    1198    1198   
2                    2147  2147                    2147    2147   
3                    1114  1114                    1114    1114   
4                    1622  1622                    1622    1622   
5                    2577  2577                    2577    2577   
6                     737   737                     737     737   
7                     471   471                     471     471   
8                    1104  1104                    1104    1104   

              relevent_experience  enrolled_university  education_level  \
company_size                                                              
1                            1198                 1198             1198   
2                            2147                 2147             2147   
3                            1114                 1114             1114   
4                            1622                 1622             1622   
5                            2577                 2577             2577   
6                             737                  737              737   
7                             471                  471              471   
8                            1104                 1104             1104   

              major_discipline  experience  company_type  last_new_job  \
company_size                                                             
1                         1198        1198          1198          1198   
2                         2147        2147          2147          2147   
3                         1114        1114          1114          1114   
4                         1622        1622          1622          1622   
5                         2577        2577          2577          2577   
6                          737         737           737           737   
7                          471         471           471           471   
8                         1104        1104          1104          1104   

              training_hours  
company_size                  
1                       1198  
2                       2147  
3                       1114  
4                       1622  
5                       2577  
6                        737  
7                        471  
8                       1104

In [60]:
data2.shape

(15021, 13)

In [61]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15021 entries, 0 to 15020
Data columns (total 13 columns):
enrollee_id               15021 non-null int64
city                      15021 non-null int64
city_development_index    15021 non-null float64
gender                    15021 non-null int64
relevent_experience       15021 non-null int64
enrolled_university       15021 non-null int64
education_level           15021 non-null int64
major_discipline          15021 non-null int64
experience                15021 non-null int64
company_size              10970 non-null object
company_type              15021 non-null object
last_new_job              15021 non-null object
training_hours            15021 non-null int64
dtypes: float64(1), int64(9), object(3)
memory usage: 1.5+ MB


In [62]:
data2['last_new_job']= label_encoder.fit_transform(data2['last_new_job']) 
data2['last_new_job'].unique()

array([0, 1, 4, 5, 3, 2], dtype=int64)

In [63]:
data2['company_type']= label_encoder.fit_transform(data2['company_type']) 
data2['company_type'].unique()

array([4, 5, 2, 1, 0, 3], dtype=int64)

In [64]:
data2= data2.astype({"city_development_index":'int64'}) 

In [65]:
data2.shape

(15021, 13)

In [66]:
data2.drop(["company_size"], axis=1, inplace=True)

In [67]:
data1.head()

city  city_development_index  gender  relevent_experience  \
0    41                       0       1                    0   
1   112                       0       1                    0   
2    48                       0       0                    0   
3    93                       0       1                    0   
4     2                       0       0                    1   

   enrolled_university  education_level  major_discipline  experience  \
0                    2                0                 5          13   
1                    2                0                 5           5   
2                    2                0                 5          16   
3                    2                0                 5           5   
4                    2                2                 5          18   

   company_type  last_new_job  training_hours  target  
0             5             0             106       0  
1             1             0              69       0  
2             4             1               4       0  
3             5             0              26       0  
4             5             1              88       1

In [68]:
data1.shape

(17315, 12)

In [69]:
data2.shape

(15021, 12)

In [70]:
data3 = data2.drop(["enrollee_id"], axis = 1)

In [71]:
data3.shape

(15021, 11)

In [72]:
pred_test = model.predict(data3)

In [73]:
submission=pd.read_csv(r"sample_submission_sxfcbdx.csv")

In [74]:
submission.head()

Empty DataFrame
Columns: [enrollee_id, target]
Index: []

In [75]:
submission_df = pd.DataFrame({'enrollee_id':data2['enrollee_id'], 'target':pred_test})
submission_df.to_csv('Sample Submission final.csv', index=False)

In [76]:
submission_df.head()

enrollee_id  target
0        16548       1
1        12036       1
2        11061       1
3         5032       0
4        17599       0

In [77]:
#pd.DataFrame(submission, columns=['enrollee_id','target']).to_csv('final submission.csv')

In [78]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test,y_predict) 

In [79]:
print('accuracy_score',score) 

accuracy_score 0.5701958181214736


In [80]:
type(pred_test)

numpy.ndarray

In [81]:
### SVM

from sklearn.svm import SVC
X = df_upsampled.drop(["target"], axis=1) 
y = df_upsampled.target   
test_size = 0.20 
seed = 100
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=seed) 
type(X_train)

pandas.core.frame.DataFrame

In [82]:
sv = SVC(kernel='rbf', C=100, gamma='auto')
sv.fit(X_train, y_train)

SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [83]:
model_score1 = sv.score(X_test, y_test)
y_predict1 = sv.predict(X_test)

# check the accuracy on the training set
print("Training accuracy svm:" ,sv.score(X_train, y_train))
print("Testing accuracy svm:", sv.score(X_test, y_test))

print(metrics.confusion_matrix(y_test, y_predict1))

Training accuracy svm: 0.9969297153763174
Testing accuracy svm: 0.9444075672087621
[[2693  307]
 [  28 2998]]


In [84]:
score_sv = accuracy_score(y_test,y_predict1)
print("accuracy score:", score_sv)

accuracy score: 0.9444075672087621


In [85]:
pred_test_sv = sv.predict(data3)

In [86]:
submission_df = pd.DataFrame({'enrollee_id':data2['enrollee_id'], 'target':pred_test_sv})
submission_df.to_csv('Sample Submission sv.csv', index=False)